export const MASTER_ACCOUNTS = {
    ASSET: [
        { code: '101', name: '현금', description: '지폐, 동전 등 즉시 사용 가능한 현금' },
        { code: '103', name: '보통예금', description: '입출금이 자유로운 은행 예금' },
        { code: '108', name: '외상매출금', description: '주된 영업활동에서 발생한 미수 채권' },
        { code: '120', name: '미수금', description: '영업활동 이외의 거래에서 발생한 채권' },
        { code: '131', name: '선급금', description: '상품 등을 인도받기 전 미리 지급한 대금' },
        { code: '133', name: '가지급금', description: '금액이나 내용이 확정되지 않은 일시적 지급' },
        { code: '146', name: '상품', description: '판매를 목적으로 구입한 물품' },
        { code: '153', name: '원재료', description: '제조를 위해 구입한 원료' },
        { code: '212', name: '비품', description: 'PC, 가구 등 사무용 집기' },
        { code: '213', name: '차량운반구', description: '영업용 및 업무용 자동차' },
        { code: '240', name: '소프트웨어', description: 'ERP, 라이선스 등 무형자산' },
        { code: '250', name: '임차보증금', description: '사무실 등 임차를 위해 예치한 보증금' },
    ],
    LIABILITY: [
        { code: '251', name: '외상매입금', description: '주된 영업활동에서 발생한 채무' },
        { code: '253', name: '미지급금', description: '영업활동 이외의 거래에서 발생한 채무' },
        { code: '254', name: '예수금', description: '급여 등에서 원천징수한 세금 및 보험료' },
        { code: '255', name: '미지급비용', description: '발생은 했으나 지급기일이 도래하지 않은 비용' },
        { code: '260', name: '단기차입금', description: '1년 이내 상환 예정인 차입금' },
        { code: '290', name: '장기차입금', description: '상환 기간이 1년 이상인 차입금' },
        { code: '261', name: '미지급세금', description: '법인세 등 확정되었으나 미납한 세금' },
        { code: '265', name: '리스부채', description: '금융리스 계약에 따른 미지급 원금' },
    ],
    EQUITY: [
        { code: '331', name: '자본금', description: '주주가 납입한 원천 자본' },
        { code: '377', name: '미처분이익잉여금', description: '처분되지 않고 남은 당기순이익 누계' },
    ],
    REVENUE: [
        { code: '401', name: '상품매출', description: '구입한 상품을 판매하여 얻은 수익' },
        { code: '404', name: '제품매출', description: '직접 제조한 제품을 판매하여 얻은 수익' },
        { code: '408', name: '서비스매출', description: '용역 제공을 통해 얻은 수익' },
        { code: '901', name: '이자수익', description: '예금 등에 대해 발생한 이자' },
        { code: '903', name: '잡이익', description: '영업외 발생한 자잘한 이익' },
    ],
    EXPENSE: [
        { code: '801', name: '급여', description: '임직원에게 지급하는 정기 보수' },
        { code: '802', name: '제수당', description: '상여금, 연차수당 등 각종 수당' },
        { code: '811', name: '복리후생비', description: '직원 식대, 경조사비, 보험료 지원' },
        { code: '812', name: '여비교통비', description: '출장비, 택시비, 시내외 교통비' },
        { code: '813', name: '통신비', description: '전화료, 인터넷료, 우편료' },
        { code: '814', name: '수도광열비', description: '전기료, 수도료, 가스료' },
        { code: '815', name: '세금과공과', description: '자동차세, 협회비, 벌금 등이 아닌 공과금' },
        { code: '816', name: '임차료', description: '사무실, 복사기 등 렌탈/임차 비용' },
        { code: '817', name: '수선비', description: '비품, 차량 등의 수리 비용' },
        { code: '818', name: '보험료', description: '자동차보험, 화재보험 등' },
        { code: '819', name: '접대비', description: '거래처 식대, 화환 등(기업업무추진비)' },
        { code: '820', name: '운반비', description: '택배비, 퀵서비스 등 물류비' },
        { code: '821', name: '교육훈련비', description: '학원비, 세미나 참가비, 도서구입비' },
        { code: '822', name: '차량유지비', description: '주유비, 주차비, 통행료' },
        { code: '823', name: '도서인쇄비', description: '도서 구입, 명함 인쇄, 신문 구독' },
        { code: '824', name: '소모품비', description: '문구류, 탕비실 비품 등 소모성 물품' },
        { code: '825', name: '지급수수료', description: '송금수수료, 세무대리비, 전문가 자문' },
        { code: '826', name: '광고선전비', description: 'SNS 광고, 전단지, 홍보 영상 제작' },
        { code: '830', name: '연구개발비', description: '기술 개발을 위해 지출한 비용' },
        { code: '831', name: '감가상각비', description: '유형자산의 가치 감소분 계상' },
        { code: '951', name: '이자비용', description: '차입금 등에 대한 이자 지급' },
        { code: '998', name: '법인세비용', description: '당기 소득에 대해 납부할 세금액' },
    ]
};

export const ALL_ACCOUNTS = [
    ...MASTER_ACCOUNTS.ASSET,
    ...MASTER_ACCOUNTS.LIABILITY,
    ...MASTER_ACCOUNTS.EQUITY,
    ...MASTER_ACCOUNTS.REVENUE,
    ...MASTER_ACCOUNTS.EXPENSE
];
