import { JournalEntry, BusinessRisk, ManagementReport, RiskLevel, RiskType, DecisionCandidate, ComplianceReview, RiskDecisionLog } from '../types';

/**
 * Management Risk Engine (Phase 4.5 & Phase 5)
 * 
 * Transforms raw signals (Journal Entries, Compliance Flags) into Executive Decision Contexts.
 * Phase 5 adds Narrative Generation based on decisions.
 */

const formatCurrency = (amount: number) => new Intl.NumberFormat('ko-KR', { style: 'currency', currency: 'KRW' }).format(amount);

export const generateNarrativeBriefing = (report: ManagementReport, decisions: RiskDecisionLog[]): string => {
    const { summary, actionItems } = report;
    const now = new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' });

    let markdown = `# 📢 경영 리스크 감사 보고서 (Executive Audit Briefing)\n`;
    markdown += `**발행일:** ${now}\n`;
    markdown += `**분석 대상:** ${report.period}\n\n`;

    markdown += `## 1. Executive Summary (요약)\n`;
    markdown += `당월 경영 활동 분석 결과, 총 **${summary.totalRisks}건**의 리스크 시그널이 감지되었습니다.\n`;
    markdown += `- 🔴 **Critical/High Risk:** ${summary.criticalCount + summary.highCount}건 (즉시 조치 필요)\n`;
    markdown += `- 🟡 **Monitoring Required:** ${actionItems.monitoring}건\n\n`;

    // Decisions Section
    const relevantDecisions = decisions.filter(d => report.risks.some(r => r.id === d.riskId));

    if (relevantDecisions.length > 0) {
        markdown += `## 2. Key Decisions (의사결정 현황)\n`;
        markdown += `경영진에 의해 현재까지 **${relevantDecisions.length}건**의 주요 의사결정이 완료되었습니다.\n\n`;

        relevantDecisions.forEach((d, idx) => {
            const risk = report.risks.find(r => r.id === d.riskId);
            markdown += `### ${idx + 1}. ${risk?.title || 'Unknown Risk'}\n`;
            markdown += `- **Decision:** ${d.decisionLabel} (by ${d.decidedBy})\n`;
            markdown += `- **Reasoning:** "${d.comment || 'N/A'}"\n`;
            markdown += `- **Status:** ✅ Action Taken\n\n`;
        });
    } else {
        markdown += `## 2. Key Decisions (의사결정 현황)\n`;
        markdown += `_현재 기록된 경영진의 의사결정 사항이 없습니다. 아래 주요 리스크에 대한 판단이 필요합니다._\n\n`;
    }

    // Pending Critical Risks
    const pendingCritical = report.risks.filter(r =>
        (r.level === 'Critical' || r.level === 'High') &&
        !decisions.some(d => d.riskId === r.id)
    );

    if (pendingCritical.length > 0) {
        markdown += `## 3. Pending Critical Actions (미결 중요 사안)\n`;
        markdown += `다음 항목들은 경영상의 심각한 영향을 줄 수 있어 즉각적인 의사결정이 요구됩니다.\n\n`;

        pendingCritical.forEach((r) => {
            markdown += `> **⚠️ ${r.title}**\n`;
            markdown += `> - **Impact:** ${r.impact}\n`;
            markdown += `> - **Action Required:** ${r.decisionCandidates[0]?.label || 'Review needed'}\n\n`;
        });
    }

    markdown += `---\n*Generated by AccountingFlow AI Audit Engine (Phase 5)*`;

    return markdown;
};

const createDecision = (type: DecisionCandidate['type'], label: string, desc: string): DecisionCandidate => ({
    id: crypto.randomUUID(),
    type,
    label,
    description: desc
});

export const analyzeManagementRisks = (ledger: JournalEntry[]): BusinessRisk[] => {
    const risks: BusinessRisk[] = [];
    const now = new Date().toISOString();

    // 1. Split Payment Detection (Internal Control Risk)
    // Logic: Same vendor, same date, multiple transactions within short time (or just count > 3)
    const vendorDateMap = new Map<string, JournalEntry[]>();

    ledger.forEach(e => {
        if (!e.vendor || !e.date) return;
        const key = `${e.vendor}|${e.date}`;
        const group = vendorDateMap.get(key) || [];
        group.push(e);
        vendorDateMap.set(key, group);
    });

    vendorDateMap.forEach((entries, key) => {
        if (entries.length >= 3) {
            // Heuristic: 3+ txns at same vendor on same day
            const totalAmt = entries.reduce((sum, e) => sum + e.amount, 0);
            const [vendor, date] = key.split('|');

            risks.push({
                id: crypto.randomUUID(),
                type: 'InternalControl',
                level: 'High',
                title: 'Potential Split Payment (분할 결제 의심)',
                description: `${date}일 ${vendor}에서 ${entries.length}건의 연속 결제(총 ${totalAmt.toLocaleString()}원)가 감지되었습니다.`,
                impact: '규정 우회 및 접대비 한도 회피 가능성 (Compliance Evasion)',
                detectedAt: now,
                relatedEntries: entries.map(e => e.id),
                status: 'Active',
                decisionCandidates: [
                    createDecision('Interview', '담당자 소명 요청', '분할 결제 사유(단순/고의) 확인 필요'),
                    createDecision('Monitor', '해당 부서 한시적 모니터링', '향후 3개월간 유사 패턴 집중 감사')
                ]
            });
        }
    });

    // 2. Weekend/Night Usage (Reputation/Compliance Risk)
    const weekendEntries = ledger.filter(e => {
        const date = new Date(e.date);
        const day = date.getDay(); // 0=Sun, 6=Sat
        return (day === 0 || day === 6) && (e.debitAccount.includes('복리') || e.debitAccount.includes('접대'));
    });

    if (weekendEntries.length > 0) {
        const total = weekendEntries.reduce((s, e) => s + e.amount, 0);
        risks.push({
            id: crypto.randomUUID(),
            type: 'Compliance',
            level: 'Medium',
            title: 'Weekend Corporate Card Usage (주말 법인카드 사용)',
            description: `주말 기간 총 ${weekendEntries.length}건, ${total.toLocaleString()}원의 법인카드 사용이 감지되었습니다.`,
            impact: '업무 연관성 입증 실패 시 비용 부인 및 세무 리스크 (Tax Disallowance)',
            detectedAt: now,
            relatedEntries: weekendEntries.map(e => e.id),
            status: 'Active',
            decisionCandidates: [
                createDecision('Policy', '주말 사용 승인 절차 강화', '사전 품의 없는 주말 사용 제한 검토'),
                createDecision('Interview', '업무 연관성 증빙 보완', '참석자 및 업무 목적 명시 요구')
            ]
        });
    }

    // 3. High Value Unclassified (Financial Risk)
    // Assume threshold 1,000,000 KRW
    const highValueSuspense = ledger.filter(e =>
        e.amount >= 1000000 &&
        ['가지급금', '가수금', '전도금'].some(k => e.debitAccount.includes(k) || e.creditAccount.includes(k)) &&
        !e.isSettled
    );

    if (highValueSuspense.length > 0) {
        const total = highValueSuspense.reduce((s, e) => s + e.amount, 0);
        risks.push({
            id: crypto.randomUUID(),
            type: 'Financial',
            level: 'Critical',
            title: 'Large Suspense Account Balance (고액 가지급금 누적)',
            description: `현재 미소명된 100만원 이상 가지급금이 ${highValueSuspense.length}건 (총 ${total.toLocaleString()}원) 존재합니다.`,
            impact: '자금 횡령 리스크 및 가지급금 인정이자 법인세 부담 증가',
            detectedAt: now,
            relatedEntries: highValueSuspense.map(e => e.id),
            status: 'Active',
            decisionCandidates: [
                createDecision('Restrict', '자금 집행 일시 중단', '소명 완료 시까지 추가 가지급 지급 중단'),
                createDecision('Interview', '최고경영진 보고 및 즉시 소명', '자금 출처 및 용도에 대한 즉각적인 감사 수행')
            ]
        });
    }

    // 4. Duplicate Payment Risk
    // Simplistic check for exact amount and vendor within same period
    // (Ideally handled by deduplication logic, but risk engine serves as a safety net)
    const amountMap = new Map<string, JournalEntry[]>();
    ledger.forEach(e => {
        const key = `${e.amount}-${e.vendor}`;
        const group = amountMap.get(key) || [];
        group.push(e);
        amountMap.set(key, group);
    });

    amountMap.forEach((entries, key) => {
        if (entries.length > 1) {
            const [amt, vendor] = key.split('-');
            risks.push({
                id: crypto.randomUUID(),
                type: 'Operational',
                level: 'Medium',
                title: 'Duplicate Payment Candidate (중복 결제 의심)',
                description: `${vendor} 거래처에 동일 금액(${Number(amt).toLocaleString()}원)이 ${entries.length}회 기록되었습니다.`,
                impact: '자금 이중 지출 (OpEx Leakage)',
                detectedAt: now,
                relatedEntries: entries.map(e => e.id),
                status: 'Active',
                decisionCandidates: [
                    createDecision('Monitor', '중복 거래 확인/취소', '실수 여부 확인 후 승인 취소'),
                ]
            });
        }
    });


    return risks;
};

export const generateManagementReport = (ledger: JournalEntry[], period: string): ManagementReport => {
    // 1. Analyze Risks
    const allRisks = analyzeManagementRisks(ledger);

    // 2. Sort by Severity
    const severityMap: Record<RiskLevel, number> = { 'Critical': 4, 'High': 3, 'Medium': 2, 'Low': 1 };
    allRisks.sort((a, b) => severityMap[b.level] - severityMap[a.level]);

    // 3. Summarize
    const criticalCount = allRisks.filter(r => r.level === 'Critical').length;
    const highCount = allRisks.filter(r => r.level === 'High').length;

    // 4. Action Items (Heuristic count)
    // Critical = Immediate, High = Immediate, Medium = Monitoring
    const immediate = criticalCount + highCount;
    const monitoring = allRisks.filter(r => r.level === 'Medium' || r.level === 'Low').length;

    return {
        generatedAt: new Date().toISOString(),
        period,
        summary: {
            totalRisks: allRisks.length,
            criticalCount,
            highCount,
            topRisks: allRisks.slice(0, 3)
        },
        risks: allRisks,
        actionItems: {
            immediate,
            monitoring
        }
    };
};
